# Generated by Django 3.0.6 on 2020-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sen',
            field=models.CharField(max_length=300),
        ),
    ]
